In [1]:
import numpy as np
import pandas as pd

In [2]:

data= pd.read_csv('mutations_encoded.tsv',sep="\t",encoding='utf-8', lineterminator='\n')

In [63]:
data.columns=['#Feature_AC' ,'Feature_short_label', 'Feature_range(s)',
 'Original_sequence' ,'Resulting_sequence' ,'Feature_type',
 'Feature_annotation' ,'Affected_protein_AC', 'Affected_protein_symbol',
 'Affected_protein_full_name' ,'Affected_protein_organism',
 'Interaction_participants', 'PubMedID', 'Figure_legend', 'Interaction_AC']

elaspicData= pd.read_csv('will_be_classified.csv')

homoSapiens=pd.DataFrame()

homoSapiens= data[data.Affected_protein_organism=='9606 - Homo sapiens'] #get homosapiens
homoSapiens= homoSapiens[homoSapiens.Feature_type !='mutation(MI:0118)']  #get correct mutations values refactor sometime!
homoSapiens= homoSapiens[homoSapiens.Feature_type != 'mutation with no effect(MI:2226)']

In [64]:
elaspicInteraction = pd.DataFrame()
elaspicInteraction = elaspicData[elaspicData.Type=='interface' ]

In [70]:
homoSapiens.head(5)

,#Feature_AC,Feature_short_label,Feature_range(s),Original_sequence,Resulting_sequence,Feature_type,Feature_annotation,Affected_protein_AC,Affected_protein_symbol,Affected_protein_full_name,Affected_protein_organism,Interaction_participants,PubMedID,Figure_legend,Interaction_AC
4355,EBI-12523581,V420A,420-420,V,A,mutation causing(MI:2227),NaN,uniPtkb:Q9P2R3,ANKFY1,NaN,9606 - Homo sapiens,"uniPtkb:Q9P2R3(Ptein(MI:0326), 9606 - Homo sap...",27189942,"8 B and C, 9A",EBI-12509450
4356,EBI-12691313,F289L,289-289,F,L,mutation causing(MI:2227),"MI:0612 (comment): Allele_ID: 2100_2792,- (rem...",uniPtkb:Q92731-3,ESR2,NaN,9606 - Homo sapiens,"intact:EBI-12691290(ds dna(MI:0681), 9606 - Ho...",25910212,Table S6B,EBI-12691308
4357,EBI-12523583,Q418K,418-418,Q,K,mutation causing(MI:2227),NaN,uniPtkb:Q9P2R3,ANKFY1,NaN,9606 - Homo sapiens,"uniPtkb:Q9P2R3(Ptein(MI:0326), 9606 - Homo sap...",27189942,"8 B and C, 9A",EBI-12509450
4358,EBI-12693334,E435K,435-435,E,K,mutation causing(MI:2227),"MI:0612 (comment): Allele_ID: 1959_17709,- (re...",intact:EBI-12690028,egr2,NaN,9606 - Homo sapiens,"intact:EBI-12693327(ds dna(MI:0681), 9606 - Ho...",25910212,Table S6B,EBI-12693329
4359,EBI-12692465,R148W,148-148,R,W,mutation causing(MI:2227),"MI:0612 (comment): Allele_ID: 51114_6216,- (re...",uniPtkb:Q9Y397,ZDHHC9,NaN,9606 - Homo sapiens,"intact:EBI-12692329(ds dna(MI:0681), 9606 - Ho...",25910212,Table S6B,EBI-12692460

In [66]:
elaspicData.head(5)

,Unnamed: 0,Input_identifier,UniProt_ID,Mutation,Status,Type,COSMIC_mut_ID,ClinVar_mut_ID,UniProt_mut_ID,Domain_name,...,number_of_residues_mut,IntraclashesEnergy1_wt,IntraclashesEnergy1_mut,IntraclashesEnergy2_wt,IntraclashesEnergy2_mut,Interface_hydrophobic_area,Interface_hydrophilic_area,Interface_total_area,Interface_contact_distance_wt,Interface_contact_distance_mut
0,0,O14893,O14893,Y52D,done,core,-,-,-,SIP1,...,248,-,-,-,-,-,-,-,-,-
1,1,O14893,O14893,Y52D,done,interface,-,-,-,SIP1,...,338,51.9403,51.8577,164.073,164.073,435.525,236.44,671.965,2.64499,2.64499
2,2,O14893,O14893,Y52D,done,interface,-,-,-,SIP1,...,324,53.3621,53.2632,36.9299,36.9299,469.205,230.435,699.64,3.85512,3.36921
3,3,P08709,P08709,R139Q,done,core,-,-,VAR_006498,EGF,...,52,-,-,-,-,-,-,-,-,-
4,4,P08709,P08709,R139Q,done,interface,-,-,VAR_006498,EGF,...,283,26.9873,26.7578,138.692,138.692,346.735,246.295,593.03,3.27446,3.27446

In [71]:
compare= pd.read_csv('compare.csv')

In [72]:
compare.head(5)

   Unnamed: 0 UniProt_ID Mutation
0           0     O14893     Y52D
1           1     O14893     Y52D
2           2     P08709    R139Q
3           3     P08709    R139Q
4           4     P08709    R139Q

In [ ]:
for i in range(len(data)):
        for k in range(len(delete)):
            if(delete.iloc[k,1]==data.iloc[i,1] and delete.iloc[k,2]==data.iloc[i,2]):
                data.iloc[i,1]='NON'